# FILENAME
# playbook_set_rule.yml
#
# DESCRIPTION
# Example playbook that will connect to the firewall using credentials provided in the vars.yml and set a simple security rule.
#
# REQUIREMENTS
# pip install ansible
# ansible-galaxy install PaloAltoNetworks.paloaltonetworks
#
# STEPS
# update vars.yml with your own credentials/settings
#
# Good practice: The var files are provided in cleartext. They should be edited and encrypred using:
# ansible-vault encrypt firewall-secrets.yml 
#
# EXECUTE
# ansible-playbook playbook_set_srule.yml
---
- hosts: localhost
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks: 
    - name: include variables (free-form)
      include_vars: vars.yml  
      no_log: 'yes'

    - name: Create an address Object
      panos_object:
        ip_address: "192.168.2.10"
        usename: "admin"
        password: "admin"
        dns_server_primary: "8.8.8.8"
      
    - name: Create NAT rule for Web server
      panos_nat_rule:
        ip_address: "{{mgmt_ip}}"
        username: "{{admin_username}}"
        password: "{{admin_password}}"
        operation: 'add'
        rule_name: "Web SSH"
        source_zone: ["external"]
        destination_zone: "external"
        source_ip: ["any"]
        destination_ip: ["10.0.0.100"]
        service: "service-tcp-221"
        snat_type: "dynamic-ip-and-port"
        snat_interface: "ethernet1/2"
        dnat_address: "10.0.1.101"
        dnat_port: "22
        
        #ip_address: "{{ mgmt_ip }}"
        #password: "{{admin_password}}"
        #operation: 'add'
        #rule_name: "SSh Permit"
        #source_zone: ["untrust"]
        #destination_zone: ["trust"]
        #source_ip: ["any"]
        #source_user: ["any"]
        #destination_ip: ["1.1.1.1"]
        #category: ["any"]
        #application: ["ssh"]
        #service: ["application_default"]
        #hip_profile: ["any"]
        #action: "allow"
        #commit: "True"

